// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmXHJQ4rhz7R_q0_yUqNVie7wMtiYO9Qo',
    appId: '1:1051490625127:web:a27cecc388b3d0ad4916c2',
    messagingSenderId: '1051490625127',
    projectId: 'sincroneasy-app',
    authDomain: 'sincroneasy-app.firebaseapp.com',
    storageBucket: 'sincroneasy-app.appspot.com',
    measurementId: 'G-5ZEF38PRRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRCH2ZXMiOZrYzYqzyuf4ZCVxuSymp08Y',
    appId: '1:1051490625127:android:b1dea52bdce860404916c2',
    messagingSenderId: '1051490625127',
    projectId: 'sincroneasy-app',
    storageBucket: 'sincroneasy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLGxDRaB551CmXupTzjQnDml49637dPWk',
    appId: '1:1051490625127:ios:90fb94058b3665a24916c2',
    messagingSenderId: '1051490625127',
    projectId: 'sincroneasy-app',
    storageBucket: 'sincroneasy-app.appspot.com',
    androidClientId: '1051490625127-c7av6ndfronp7ouijm7m2gr1r3shbiv0.apps.googleusercontent.com',
    iosClientId: '1051490625127-csaiv6rncc7bti1dpttk7du2cqq5mr79.apps.googleusercontent.com',
    iosBundleId: 'com.example.sincroneasy',
  );
}
