// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk6PSN8txk3sov-sewB_4YnlHcGGa7FGU',
    appId: '1:437561916381:web:a1c5206f3faaa8415f1434',
    messagingSenderId: '437561916381',
    projectId: 'firebase-ofc',
    authDomain: 'fir-ofc.firebaseapp.com',
    storageBucket: 'firebase-ofc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEJPsZ9WiKxYKlLTSQoJup0r5jRdSzUGc',
    appId: '1:437561916381:android:e4e8ed5157479a135f1434',
    messagingSenderId: '437561916381',
    projectId: 'firebase-ofc',
    storageBucket: 'firebase-ofc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGJwAV1hnCDNR5DdfPZEYu-4g7AVBNeOA',
    appId: '1:437561916381:ios:cc038a899efee4b65f1434',
    messagingSenderId: '437561916381',
    projectId: 'firebase-ofc',
    storageBucket: 'firebase-ofc.appspot.com',
    iosClientId: '437561916381-6qo7fnc44fes9pvrd2mpiinp71dd00r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sincroneasy',
  );
}
